### ISSUE TITLE
A vast collection of quotes from various categories and authors

### ISSUE THREAD

**Issue by Jenil17** [itsaakashpatel/quote-flora#1]
“As a user, I want a vast collection of quotes from various categories and authors”

**Comment by itsaakashpatel** [comment]
This will add theme packages and set up a database of quotes from various categories and authors. There will be multiple PRs here.

**### Checklist:**

- [x] Add `React native paper` for UI elements: https://github.com/itsaakashpatel/quote-flora/pull/28
- [x] Add theme provider.
- [x] Add a `src` folder to ensure everything stays in one place.
- [x] Add `authors.json`, `quote.json`, and `categories.json` to the `data` folder for accessing quotes. 

Final commit : https://github.com/itsaakashpatel/quote-flora/commit/1652267f809bf1ba872e2bf83e08e981f6893253
