### ISSUE TITLE
Save quotes as images to your device's gallery for easy access and sharing

### ISSUE THREAD

**Issue by Jenil17** [itsaakashpatel/quote-flora#10]

**Comment by itsaakashpatel** [comment]
This is quite similar to https://github.com/itsaakashpatel/quote-flora/issues/12

As we are not building a complex app that fetches data from the internet, quotes are already being managed offline on the user's device. Hence, it did not require any additional effort to build such a feature.

Alternative feature we added here: https://github.com/itsaakashpatel/quote-flora/issues/37
